config/routes.rb
Rails.application.routes.draw do
  devise_for :users
# resources :sessions
  resources :users
  root "homes#index"

  get "dashboard" => 'dashboards#index', :as => :dashboard_page

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # Association
  has_many :categories
  has_many :products
  
  #Devise
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  #Validation
  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  #instance method
  def set_default_role
    self.role ||= :user
  end

  def full_name
    "#{first_name}" "#{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout 'application'
  protect_from_forgery
  before_action :configure_permitted_parameters, if: :devise_controller?

protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name,:last_name,:role,:username,:email,:password,:password_confirmation,:remember_me) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:login,:first_name,:last_name,:role,:username,:email,:password,:remember_me)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name,:last_name,:role,:username,:email,:password,:password_confirmation,:current_password) }
  end


end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, only:[:new,:edit,:update,:destroy]

  def index

  end
end

app/controllers/homes_controller.rb
class HomesController < NewBootstrapController


  def index

  end


end

app/controllers/new_bootstrap_controller.rb
class NewBootstrapController < ActionController::Base
  layout 'new_application'
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
    @fields = ["ID","Username","Email","Phone","Address","Role","Position","Date Of Birth","Image","Created_At","Updated_At"]
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to root_path, :alert => "Access denied."
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

    def admin_only
      unless current_user.admin?
        redirect_to root_path, :alert => "Access denied."
      end
    end

    def secure_params
      params.require(:user).permit(:username,:email,:password,:password_confirmation,
                                    :role,:description,:image,:position,:dateofbirth,
                                    :address,:phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= ""
    options[:message] ||= ""
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/homes_helper.rb
module HomesHelper


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboards/index.html.erb
<%=render "shared/navbar"%>

<section>
  <div class="mainwrapper">
    <%=render "shared/left-panel"%>
      <div class="mainpanel">
        <div class="contentpanel">
          <div class="row row-stat">
      				<div class="col-md-3">
                <div class="panel noborder">
                  <div class="panel-heading noborder">
                    <div class="panel-btns">
                      <a href="#" class="panel-close tooltips" data-toggle="tooltip" title="Close Panel"><i class="fa fa-times"></i></a>
                    </div><!-- panel-btns -->

                    <%=link_to new_user_path do%>
                      <div class="panel-icon icon-user"><i class="fa fa-user"></i></div>
                    <%end%>

                    <div class="media-body">
                      <h3 class="mt5" style="font-size:17px;">Add User</h3>
                      <h5 class="md-title nomargin">Users</h5>
                    </div><!-- media-body -->

                  </div><!-- panel-body -->
                </div><!-- panel -->
              </div><!-- col-md-3 -->

            </div><!-- row -->

            <div class="row">

      				<div class="col-md-8">
      					<section class="panel panel-default">
      						<div class="panel-body weather-row">
      							<img src="/weather_image.jpg" height="243" alt="">
      							<div class="weather-head">
      								weather forecast
      							</div>
      							<div class="form-group country-select">
      								<select class="width100p" data-placeholder="New York">
      									<option value="">New York</option>
      									<option value="">London</option>
      									<option value="">Australia</option>
      									<option value="">Canada</option>
      									<option value="">China</option>
      									<option value="">New York</option>
      								</select>
      							</div>
      						</div>

      				<div class="panel-footer">
      					<div class="row weather-full-info">
      						<div class="col-md-3 today-status">
      							<h1>Today</h1>
      							<span class="wi wi-day-cloudy"></span>
      							<div class="degree">37</div>
      						</div>
      						<div class="col-md-9">
      							<ul>
      								<li>
      									<h2>Tomorrow</h2>
      									<span class="wi wi-day-cloudy text-primary"></span>
      									<div class="statistics">32</div>
      								</li>
      								<li>
      									<h2>Mon</h2>
      									<span class="wi wi-day-cloudy text-danger"></span>
      									<div class="statistics">40</div>
      								</li>
      								<li>
      									<h2>Tue</h2>
      									<span class="wi wi-day-cloudy text-info"></span>
      									<div class="statistics">25</div>
      								</li>
      								<li>
      									<h2>Wed</h2>
      									<span class="wi wi-day-cloudy text-success"></span>
      									<div class="statistics">37</div>
      								</li>
      								<li>
      									<h2>Thu</h2>
      									<span class="wi wi-day-cloudy text-warning"></span>
      									<div class="statistics">15</div>
      								</li>
      								<li>
      									<h2>Fri</h2>
      									<span class="wi wi-day-cloudy"></span>
      									<div class="statistics">21</div>
      								</li>
      							</ul>
      						</div>
      					</div>
      				</div>
      			</section>
      		</div>

      		<div class="col-md-4">
      			<section class="panel panel-default">
      				<div class="clock-panel">
      					<h1>DECEMBER 16</h1>
      					<p class="text-left">2016, Friday</p>
      					<p class="text-left">7:53 PM</p>
      				</div>

      				<ul id="clock">
      					<li id="sec"></li>
      					<li id="hour"></li>
      					<li id="min"></li>
      				</ul>

      				<ul class="clock-category">
      					<li>
      						<a href="#" class="active">
      							<i class="fa fa-clock-o"></i>
      							<span>Clock</span>
      						</a>
      					</li>
      					<li>
      						<a href="#">
      							<i class="fa fa-clock-o"></i>
      							<span>Alarm</span>
      						</a>
      					</li>
      					<li>
      						<a href="#">
      							<i class="fa fa-clock-o"></i>
      							<span>Stop watch</span>
      						</a>
      					</li>
      					<li>
      						<a href="#">
      							<i class="fa fa-clock-o"></i>
      							<span>Timer</span>
      						</a>
      					</li>
      				</ul>
      			</section>
      		</div>
      	</div>
        <div class="row">
          <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-body padding15">
                  <h5 class="md-title mt0 mb10">Site Statistics</h5>
                  <div id="basicFlotLegend" class="flotLegend"></div>
                  <div id="basicflot" class="flotChart"></div>
                </div><!-- panel-body -->

                <div class="panel-footer">
                  <div class="tinystat pull-left">
                    <div id="sparkline" class="chart mt5"></div>
                      <div class="datainfo">
                        <span class="text-muted">Average</span>
                        <h4>$9,201</h4>
                      </div>
                  </div><!-- tinystat -->

                  <div class="tinystat pull-right">
                    <div id="sparkline2" class="chart mt5"></div>
                      <div class="datainfo">
                        <span class="text-muted">Total</span>
                        <h4>$8,201</h4>
                      </div>
                  </div><!-- tinystat -->
                </div><!-- panel-footer -->
            </div><!-- panel -->
          </div>

          <div class="col-md-4">
              <div class="panel panel-default">
                  <div class="panel-body padding15">
                      <h5 class="md-title mt0 mb10">Site Visitors</h5>
                      <div id="basicFlotLegend2" class="flotLegend"></div>
                      <div id="basicflot2" class="flotChart"></div>
                  </div><!-- panel-body -->
                  <div class="panel-footer">
                      <div class="tinystat pull-left">
                          <div id="sparkline3" class="chart mt5"></div>
                          <div class="datainfo">
                              <span class="text-muted">Average</span>
                              <h4>52,201</h4>
                          </div>
                      </div><!-- tinystat -->
                      <div class="tinystat pull-right">
                          <div id="sparkline4" class="chart mt5"></div>
                          <div class="datainfo">
                              <span class="text-muted">Total</span>
                              <h4>11,201</h4>
                          </div>
                      </div><!-- tinystat -->
                  </div><!-- panel-footer -->
              </div><!-- panel -->
          </div>

          <div class="col-md-4">
              <div class="panel panel-default">
                  <div class="panel-body padding15">
                      <h5 class="md-title mt0 mb10">Site Impressions</h5>
                      <div id="basicFlotLegend3" class="flotLegend"></div>
                      <div id="basicflot3" class="flotChart"></div>
                  </div><!-- panel-body -->
                  <div class="panel-footer">
                      <div class="tinystat pull-left">
                          <div id="sparkline5" class="chart mt5"></div>
                          <div class="datainfo">
                              <span class="text-muted">Average</span>
                              <h4>37,101</h4>
                          </div>
                      </div><!-- tinystat -->
                      <div class="tinystat pull-right">
                          <div id="sparkline6" class="chart mt5"></div>
                          <div class="datainfo">
                              <span class="text-muted">Total</span>
                              <h4>18,899</h4>
                          </div>
                      </div><!-- tinystat -->
                  </div><!-- panel-footer -->
              </div><!-- panel -->
          </div>
        </div><!-- row -->
      </div><!-- contentpanel -->

      <%=render "shared/footer"%>
    </div><!-- mainpanel -->
  </div><!-- mainwrapper -->
</section>

app/views/shared/_footer.html.erb
<footer><!-- footer -->
  <p class="col-xs-12 footer-copyright">
    Powered by <b>Chhouk Tit Panhara</b>
  </p>
</footer>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<%=render "shared/navbar"%>

	<section>
			<div class="mainwrapper">
				<%=render "shared/left-panel"%>

					<div class="mainpanel">
							<div class="contentpanel contentpanel-wizard">
                <div class="row" style="background:#fff;padding:10px;-moz-border-radius: 3px;-webkit-border-radius: 3px;border-radius: 3px;margin-bottom:15px;">
                  <div class="col-md-12">
                    <h5 class="lg-title mb5">Table With Actions</h5>
                    <p class="mb20">An example of table with actions in every rows.</p>
                    <div class="table-responsive">
	                    <table class="table mb30">
	                      <thead>
	                        <tr>
														<%@fields.each do |f|%>
															<th><%=f%></th>
														<%end%>
	                        </tr>
	                      </thead>
												<%@users.each do |user|%>
	                      <tbody>
	                        <tr>
	                          <td><%=user.id%></td>
	                          <td><%=user.username%></td>
	                          <td><%=user.email%></td>
	                          <td><%=user.phone%></td>
														<td><%=user.address%></td>
														<td><%=user.role%></td>
														<td><%=user.position%></td>
														<td><%=user.dateofbirth%></td>
														<td><%=user.full_name%></td>
														<td><%=image_tag(user.image, :class=>"img-table-data")%></td>
														<td><%=user.created_at%></td>
														<td><%=user.updated_at%></td>
	                          <td class="table-action">
															<%if current_user.try(:admin?)%>
																<%=link_to user,:title=>"View",:class=>"tooltips" do %>
																<i class="fa fa-eye"></i>
																<%end%>
																<%=link_to edit_user_path(user),:title=>"Edit",:class=>"tooltips" do %>
																<i class="fa fa-pencil"></i>
																<%end%>
																<%=link_to user,method: :delete,data: {confirm: "Are You Sure?"},:title=>"Delete",:class=>"delete-row tooltips" do %>
																<i class="fa fa-trash-o"></i>
																<%end%>

																<%else%>
																<%=link_to user,:title=>"View",:class=>"tooltips" do %>
																<i class="fa fa-eye"></i>
																<%end%>

															<%end%>

	                          </td>
	                        </tr>
	                      </tbody>
												<%end%>
	                    </table>
                    </div><!-- table-responsive -->
                  </div><!-- col-md-6 -->
                </div>

                <div class="row">

                  <div class="col-md-8">
                    <section class="panel panel-default">
                      <div class="panel-body weather-row">
                        <img src="/weather_image.jpg" height="243" alt="">
                        <div class="weather-head">
                          weather forecast
                        </div>
                        <div class="form-group country-select">
                          <select class="width100p" data-placeholder="New York">
                            <option value="">New York</option>
                            <option value="">London</option>
                            <option value="">Australia</option>
                            <option value="">Canada</option>
                            <option value="">China</option>
                            <option value="">New York</option>
                          </select>
                        </div>
                      </div>

                  <div class="panel-footer">
                    <div class="row weather-full-info">
                      <div class="col-md-3 today-status">
                        <h1>Today</h1>
                        <span class="wi wi-day-cloudy"></span>
                        <div class="degree">37</div>
                      </div>
                      <div class="col-md-9">
                        <ul>
                          <li>
                            <h2>Tomorrow</h2>
                            <span class="wi wi-day-cloudy text-primary"></span>
                            <div class="statistics">32</div>
                          </li>
                          <li>
                            <h2>Mon</h2>
                            <span class="wi wi-day-cloudy text-danger"></span>
                            <div class="statistics">40</div>
                          </li>
                          <li>
                            <h2>Tue</h2>
                            <span class="wi wi-day-cloudy text-info"></span>
                            <div class="statistics">25</div>
                          </li>
                          <li>
                            <h2>Wed</h2>
                            <span class="wi wi-day-cloudy text-success"></span>
                            <div class="statistics">37</div>
                          </li>
                          <li>
                            <h2>Thu</h2>
                            <span class="wi wi-day-cloudy text-warning"></span>
                            <div class="statistics">15</div>
                          </li>
                          <li>
                            <h2>Fri</h2>
                            <span class="wi wi-day-cloudy"></span>
                            <div class="statistics">21</div>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </section>
              </div>

              <div class="col-md-4">
                <section class="panel panel-default">
                  <div class="clock-panel">
										<p><%=DateTime.now%></p>
                  </div>

                  <ul id="clock">
                    <li id="sec"></li>
                    <li id="hour"></li>
                    <li id="min"></li>
                  </ul>

                  <ul class="clock-category">
                    <li>
                      <a href="#" class="active">
                        <i class="fa fa-clock-o"></i>
                        <span>Clock</span>
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <i class="fa fa-clock-o"></i>
                        <span>Alarm</span>
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <i class="fa fa-clock-o"></i>
                        <span>Stop watch</span>
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <i class="fa fa-clock-o"></i>
                        <span>Timer</span>
                      </a>
                    </li>
                  </ul>
                </section>
              </div>
            </div>
					</div><!-- contentpanel -->
					<%=render "shared/footer"%>
				</div><!-- mainpanel -->
		</div><!-- mainwrapper -->
	</section>

app/views/users/show.html.erb
<%=render "shared/navbar"%>
          <section>
            <div class="mainwrapper">
              <%=render "shared/left-panel"%>
                <div class="mainpanel">
                  <div class="contentpanel">
                    <section class="panel panel-default">
                      <div class="weather-row">
                      <div class="wrapper wrapper-content animated fadeInRight">
                        <div class="row">
                            <div class="col-lg-12">

                                <div class="ibox product-detail">
                                    <div class="ibox-content">

                                        <div class="row">
                                            <div class="col-md-5">
                                                <div class="product-images">
                                                  <%if @user.image.blank?%>
                                                    <div>
                                                      <div class="image-imitation">
                                                        Image Not Found
                                                      </div>
                                                    </div>
                                                    <%else%>
                                                    <div>
                                                      <div class="image-imitation">
                                                        <%=@user.image%>
                                                      </div>
                                                    </div>
                                                  <%end%>

                                                </div>
                                            </div>
                                            <div class="col-md-7">

                                              <h4>Username</h4>

                                              <div class="small text-muted">
                                                <%=@user.username%>
                                              </div>
                                              <hr>

                                              <h4>Date Of Birth</h4>

                                              <div class="small text-muted">
                                                <%=@user.dateofbirth%>
                                              </div>
                                              <hr>

                                              <h4>Email</h4>

                                              <div class="small text-muted">
                                                <%=@user.email%>
                                              </div>
                                              <hr>

                                              <h4>Position</h4>

                                              <div class="small text-muted">
                                                <%=@user.position%>
                                              </div>
                                              <hr>

                                              <h4>Role</h4>

                                              <div class="small text-muted">
                                                <%=@user.role%>
                                              </div>
                                              <hr>

                                              <h4>Address</h4>

                                              <div class="small text-muted">
                                                <%=@user.address%>
                                              </div>
                                              <hr>

                                                <h4>Description</h4>
                                                <div class="small text-muted">
                                                  <%if @user.description.blank?%>
                                                    <p>No Description</p>
                                                    <%else%>
                                                    <%=@user.description%>
                                                  <%end%>

                                                </div>

                                                <hr>

                                                <div>
                                                    <div class="btn-group">
                                                      <% if current_user.try(:admin?) %>
                                                        <%= link_to edit_user_path, :class => 'btn btn-primary btn-sm',:rel=>"tooltip",:title=>"Edit",:style=>"margin-right:10px;" do %>
                                                          <i class="fa fa-pencil" style="font-size: 15px;"></i> Edit Product
                                                        <% end %>

                                                        <%= link_to @user,method: :delete,data: {confirm: "Are You Sure?"}, :class => 'btn btn-danger btn-sm',:rel=>"tooltip",:title=>"Delete" do %>
                                                          <i class="fa fa-trash-o" style="font-size: 15px;"></i> Delete
                                                        <% end %>
                                                      <%end%>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>

                                    </div>
                                    <div class="ibox-footer">
                                        <span class="pull-right">
                                            Created At- <i class="fa fa-clock-o"></i> <%=@user.created_at%>
                                        </span>
                                        The description
                                    </div>
                                </div>

                            </div>
                        </div>
                      </div>
                      </div>
                    </section>
                    <div class="row">
                			<div class="col-md-8">
                				<section class="panel panel-default">
                					<div class="panel-body weather-row">
                							<img src="/weather_image.jpg" height="243" alt="">
                							<div class="weather-head">
                								weather forecast
                							</div>
                							<div class="form-group country-select">
                								<select class="width100p" data-placeholder="New York">
                									<option value="">New York</option>
                									<option value="">London</option>
                									<option value="">Australia</option>
                									<option value="">Canada</option>
                									<option value="">China</option>
                									<option value="">New York</option>
                								</select>
                							</div>
                						</div>

                				<div class="panel-footer">
                					<div class="row weather-full-info">
                						<div class="col-md-3 today-status">
                							<h1>Today</h1>
                							<span class="wi wi-day-cloudy"></span>
                							<div class="degree">37</div>
                						</div>
                						<div class="col-md-9">
                							<ul>
                								<li>
                									<h2>Tomorrow</h2>
                									<span class="wi wi-day-cloudy text-primary"></span>
                									<div class="statistics">32</div>
                								</li>
                								<li>
                									<h2>Mon</h2>
                									<span class="wi wi-day-cloudy text-danger"></span>
                									<div class="statistics">40</div>
                								</li>
                								<li>
                									<h2>Tue</h2>
                									<span class="wi wi-day-cloudy text-info"></span>
                									<div class="statistics">25</div>
                								</li>
                								<li>
                									<h2>Wed</h2>
                									<span class="wi wi-day-cloudy text-success"></span>
                									<div class="statistics">37</div>
                								</li>
                								<li>
                									<h2>Thu</h2>
                									<span class="wi wi-day-cloudy text-warning"></span>
                									<div class="statistics">15</div>
                								</li>
                								<li>
                									<h2>Fri</h2>
                									<span class="wi wi-day-cloudy"></span>
                									<div class="statistics">21</div>
                								</li>
                							</ul>
                						</div>
                					</div>
                				</div>
                			</section>
                		</div>

                		<div class="col-md-4">
                			<section class="panel panel-default">
                				<div class="clock-panel">
                					<h1>DECEMBER 16</h1>
                					<p class="text-left">2016, Friday</p>
                					<p class="text-left">7:53 PM</p>
                				</div>

                				<ul id="clock">
                					<li id="sec"></li>
                					<li id="hour"></li>
                					<li id="min"></li>
                				</ul>

                				<ul class="clock-category">
                					<li>
                						<a href="#" class="active">
                							<i class="fa fa-clock-o"></i>
                							<span>Clock</span>
                						</a>
                					</li>
                					<li>
                						<a href="#">
                							<i class="fa fa-clock-o"></i>
                							<span>Alarm</span>
                						</a>
                					</li>
                					<li>
                						<a href="#">
                							<i class="fa fa-clock-o"></i>
                							<span>Stop watch</span>
                						</a>
                					</li>
                					<li>
                						<a href="#">
                							<i class="fa fa-clock-o"></i>
                							<span>Timer</span>
                						</a>
                					</li>
                				</ul>
                			</section>
                		</div>
                	</div>

                </div><!-- contentpanel -->

                <%=render "shared/footer"%>
              </div><!-- mainpanel -->
            </div><!-- mainwrapper -->
          </section>